### ISSUE TITLE
Setup difficulties

### ISSUE THREAD

**Issue by meerfrau** [WEgeophysics/pycsamt#68]
Hi Daniel,

I'm trying to install pycsamt with `python setup.py build` under Python 3.10

errors.log must exist or setup fails:
`FileNotFoundError: [Errno 2] No such file or directory: './pyCSAMT/pycsamt/_loggerfiles/errors.log'`

Then my GDAL is not detected, despite being present and working well:
```
Ignore GDAL as it is not working. Will use pyproj
error in pycsamt setup command: 'NoneType' object has no attribute 'group'
```

**Comment by WEgeophysics** [comment]
> Hi Daniel,
> 
> I'm trying to install pycsamt with `python setup.py build` under Python 3.10
> 
> errors.log must exist or setup fails: `FileNotFoundError: [Errno 2] No such file or directory: './pyCSAMT/pycsamt/_loggerfiles/errors.log'`
> 
> Then my GDAL is not detected, despite being present and working well:
> 
> ```
> Ignore GDAL as it is not working. Will use pyproj
> error in pycsamt setup command: 'NoneType' object has no attribute 'group'
> ```

You mentioned two problems: 
- 1) Missing the folder `_loggerfiles` . 
-The logging module expects a folder called `_loggerfiles` .  The error comes 
  from the logging configuration of ``p.configlog.yml``

```default 
    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: pycsamt/_loggerfiles/errors.log
        maxBytes: 1000000 # 1MB
        backupCount: 2
        encoding: utf8
```
  You can clone the new version of the repo then you will get everything fixed.

-2)  second problem: GDAL not set  
-  Install manually GDAL is a little bit complicated. To see where the warnings comes, check the decorator 
   ``gdal_data_check``. in :func:`pycsamt.utils.decorator`.  To let `pycsamt`` recognizes the GDAL, you must set a  GDAL Environment variable as :: 

```python 
   import os 
    os.environ['GDAL_DATA'] = <output>
``` 
where `output` is the GDAL file location in your local machine.  If you use Window system, you can manually set the Environmental variable : `System Properties --> Environment Variables`
